### PR TITLE
Export fixed-size versions of HPKE

### LINKED ISSUE #419: Fixed sized APIs for HKDF
Can you file an issue to add a fixed sized APIs for HKDF, or something where we pass in the output?

_Originally posted by @franziskuskiefer in https://github.com/cryspen/libcrux/pull/401#discussion_r1682321435_

### PR DESCRIPTION
**Pull request by keks**
Closes #419

### CODE REVIEW

File: libcrux-hkdf/src/impl_hacl.rs [hunk 1]
```diff
@@ -1,77 +1,17 @@
...
-        Self::expand_vec(&prk, info, okm_len)
-    }
-}
+use crate::{Algorithm, Error, HkdfMode};
 
 macro_rules! impl_hkdf {
-    ($sname:ident,$name:ident, $mode:path, $extract:ident, $expand:ident,$hash_len:literal) => {
-        pub struct $sname;
+    ($struct_name:ident,$name:ident, $string_name:literal, $mode:path, $extract:ident, $expand:ident,$hash_len:literal) => {
+        #[doc = "Implemantation of HKDF backed by"]
```
Comment (jschneider-bensch) [inline libcrux-hkdf/src/impl_hacl.rs:7]:
```suggestion
        #[doc = "Implementation of HKDF backed by "]
```
You're combining with `$string_name`, right? I've also added a space there at the end of this first part.

File: libcrux-hkdf/src/hkdf.rs [hunk 2]
```diff
@@ -8,7 +8,69 @@ pub mod hacl;
...
+    /// The result is written to `prk`.
+    ///
+    /// Note that this function panics if `salt` or `ikm` is longer than  (2**32 - 1) bytes.
+    fn extract(prk: &mut [u8; HASH_LEN], salt: &[u8], ikm: &[u8]) -> Result<(), Error>;
+
+    /// HKDF expand using the pre-key material `prk` and `info`. The output length
+    /// is defined through the type of the `okm` parameter, that the output is written to.
+    ///
+    /// Returns nothing on success.
+    /// Returns [`Error::OkmTooLarge`] if the requested `okm_len` is too large.
```
Comment (jschneider-bensch) [inline libcrux-hkdf/src/hkdf.rs:27]:
```suggestion
    /// Returns [`Error::OkmTooLarge`] if the requested `OKM_LEN` is too large.
```

File: libcrux-hkdf/src/hkdf.rs [hunk 3]
```diff
@@ -8,7 +8,69 @@ pub mod hacl;
...
+        prk: &[u8],
+        info: &[u8],
+    ) -> Result<(), Error>;
+
+    /// HKDF expand using the pre-key material `prk` and `info`. The output length
+    /// is defined by the parameter `okm_len`.
+    ///
+    /// Returns the key material in an array of length `okm_len` on success.
+    /// Returns [`Error::OkmTooLarge`] if the requested `okm_len` is too large.
+    /// Returns [`Error::ArgumentsTooLarge`] if `salt` or `ikm` is longer than
```
Comment (jschneider-bensch) [inline libcrux-hkdf/src/hkdf.rs:41]: Same thing about `salt`.

File: libcrux-hkdf/src/hkdf.rs [hunk 4]
```diff
@@ -8,7 +8,69 @@ pub mod hacl;
...
+    ///
+    /// Note that this function panics if `salt` or `ikm` is longer than  (2**32 - 1) bytes.
+    fn extract(prk: &mut [u8; HASH_LEN], salt: &[u8], ikm: &[u8]) -> Result<(), Error>;
+
+    /// HKDF expand using the pre-key material `prk` and `info`. The output length
+    /// is defined through the type of the `okm` parameter, that the output is written to.
+    ///
+    /// Returns nothing on success.
+    /// Returns [`Error::OkmTooLarge`] if the requested `okm_len` is too large.
+    /// Returns [`Error::ArgumentsTooLarge`] if one of `salt` or `ikm` are longer than, or
```
Comment (jschneider-bensch) [inline libcrux-hkdf/src/hkdf.rs:28]:
```suggestion
    /// Returns [`Error::ArgumentsTooLarge`] if  `ikm` is longer than, or
```

Since there's no `salt` argment here.

**Review by jschneider-bensch — CHANGES_REQUESTED** [review]
Looks good to me! Just some nits about the docs.

**Review by jschneider-bensch — APPROVED** [review]
Looks good, thanks!
